export const webClientId = '359972006564-9tngmtaigit300v7kqjr48sph3apvq38.apps.googleusercontent.com';
export const googleIdentityScope = ['profile', 'https://www.googleapis.com/auth/calendar'];
export const lightBlueColor = '#79a2d2';
export const blueColor = '#1473E6';
export const darkBlueColor = '#0E4BAA';
export const orangeColor = '#FF9F1C';
export const darkOrangeColor = '#FF621C';
export const redColor = '#b80000';
export const gradientColors = [blueColor, darkBlueColor];