version: 2
jobs:
  jest:
    working_directory: ~/Kalend
    docker:
      - image: circleci/node:8
    steps:
      - checkout:
          path: ~/Kalend

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: Jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test --detectOpenHandles --forceExit
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

  android:
    working_directory: ~/Kalend
    docker:
      - image: circleci/android:api-27-node8-alpha
    environment:
      - JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
          path: ~/Kalend

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: jars-v2-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}

      - run: yarn install

      - run:
          name: Chmod permissions
          command: cd android && chmod +x ./gradlew

      - run:
          name: Explicitly install platforms;android-26
          command: echo "Y" | sdkmanager "platforms;android-26"

      - run:
          name: Download Dependencies
          command: cd android && ./gradlew androidDependencies

      - run:
          name: Builds
          command: cd android && ./gradlew assembleRelease

      - save_cache:
          key: jars-v2-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
          paths:
            - ~/.gradle

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - store_artifacts:
          path: android/app/build/outputs/apk/release/
          destination: apks/

  publish-github-release:
    working_directory: ~/Kalend
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  node-android:
    jobs:
      - jest
      - android:
          requires:
            - jest
      - publish-github-release:
          requires:
            - android
