# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Kalend' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Kalend
  pod 'React', :path => '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'ART',
    'RCTImage',
  ]
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'GoogleSignIn'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/RemoteConfig', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'Firebase/Performance', '~> 5.15.0'
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-safari-view', :path => '../node_modules/react-native-safari-view'

  target 'KalendTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
