// LOGIN
export const SIGNED_IN = 'SIGNED_IN';
export const SIGNED_OUT = 'SIGNED_OUT';

// ADD
export const ADD_FE = 'ADD_FE';
export const ADD_NFE = 'ADD_NFE';
export const ADD_COLORS = 'ADD_COLORS';
export const ADD_GENERATED_NFE = 'ADD_GENERATED_NFE';
export const ADD_GENERATED_CALENDAR = 'ADD_GENERATED_CALENDAR';
export const ADD_COURSE = 'ADD_COURSE';

// DELETE
export const DELETE_NFE = 'DELETE_NFE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_FE = 'DELETE_FE';
export const DELETE_GENERATED_CALENDAR = 'DELETE_GENERATED_CALENDAR';

// CREATE
export const CREATE_CALENDAR = 'CREATE_CALENDAR';

// UPDATE
export const UPDATE_FE = 'UPDATE_FE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_NFE = 'UPDATE_NFE';

// GET
export const GET_SCHOOL_INFORMATION = 'GET_SCHOOL_INFORMATION';
export const GET_GENERATED_CALENDAR = 'GET_GENERATED_CALENDAR';


// CLEAR
export const CLEAR_FE = 'CLEAR_FE';
export const CLEAR_NFE = 'CLEAR_NFE';
export const CLEAR_SELECTED_SCHEDULE = 'CLEAR_SELECTED_SCHEDULE';
export const CLEAR_IMG = 'CLEAR_IMG';
export const CLEAR_COURSE = 'CLEAR_COURSE';
export const CLEAR_DASHBOARD_DATA = 'CLEAR_DASHBOARD_DATA';
export const CLEAR_GENERATED_CALENDAR = 'CLEAR_GENERATED_CALENDAR';
export const CLEAR_GENERATED_NFE = 'CLEAR_GENERATED_NFE';
export const CLEAR_CALENDAR = 'CLEAR_CALENDAR';
export const CLEAR_NAV_SCREEN = 'CLEAR_NAV_SCREEN';
export const CLEAR_SCHEDULE = 'CLEAR_SCHEDULE';
export const CLEAR_SCHOOL_INFORMATION = 'CLEAR_SCHOOL_INFORMATION';
export const CLEAR_UNAVAILABLE_HOURS = 'CLEAR_UNAVAILABLE_HOURS';
export const CLEAR_SETTINGS = 'CLEAR_SETTINGS';
export const CLEAR_BOTTOM_STRINGS = 'CLEAR_BOTTOM_STRINGS';
export const CLEAR_TUTORIAL_STATUS ='CLEAR_TUTORIAL_STATUS';

// SET
export const SET_IMG = 'SET_IMG';
export const SET_NAV_SCREEN = 'SET_NAV_SCREEN';
export const SET_SELECTED_SCHEDULE = 'SET_SELECTED_SCHEDULE';
export const SET_BOTTOM_STRINGS = 'SET_BOTTOM_STRINGS';
export const SET_NONFIXED_COLOR = 'SET_NONFIXED_COLOR';
export const SET_COURSE_COLOR = 'SET_COURSE_COLOR';
export const SET_FIXED_COLOR = 'SET_FIXED_COLOR';
export const SET_CALENDAR_COLOR = 'SET_CALENDAR_COLOR';
export const SET_DASHBOARD_DATA = 'SET_DASHBOARD_DATA';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_SCHOOL_INFORMATION = 'SET_SCHOOL_INFORMATION';
export const SET_TUTORIAL_STATUS = 'SET_TUTORIAL_STATUS';
export const SET_UNAVAILABLE_HOURS = 'SET_UNAVAILABLE_HOURS';
export const SET_SELECTED_CALENDAR = 'SET_SELECTED_CALENDAR';
